### ISSUE TITLE
想请教一下怎么把加速模式的录像分析打开

### ISSUE THREAD

**Issue by lux032** [SonodaHanami/Steam_watcher#1]
想请教一下怎么把加速模式的录像分析打开
因为现在都是老年人了基本上都是在打加速比较需要这个功能

**Comment by SonodaHanami** [comment]
录像分析完全交由OpenDota执行，并直接使用其分析结果。
我看了我最近打的加速的战报，要素上都是完整的（装备购买时间和控制时间等）。
如果说分析结果不完整的话应该是OpenDota方面有问题。你可以发一下录像编号和对应的程序运行日志看看具体是什么问题。
